name: COMPONENTS - CI/CD
on:
  push:
    branches:
      - main
    paths:
      - 'components/**'

jobs:
  deploy:
    name: DEPLOY DO COMPONENTS
    runs-on: ubuntu-latest
 
    steps:
    - name: Checkout código
      uses: actions/checkout@v3

    - name: Teste de execução
      run: echo 'Execução do COMPONENTS'

    - name: LISTAR TUDO
      run: ls -la

    - name: LISTAR DIR
      run: ls -la components/
 