name: FRONTEND - CI/CD
on:
  push:
    branches:
      - main
    paths:
      - 'apps/frontend/**'

jobs:
  deploy:
    name: DEPLOY DO FRONTEND
    runs-on: ubuntu-latest
 
    steps:
    - name: Checkout código
      uses: actions/checkout@v3

    - name: Teste de execução
      run: echo 'Execução do ADMIN'

    - name: LISTAR TUDO
      run: ls -la

    - name: LISTAR DIR
      run: ls -la apps/frontend/
 